### ISSUE TITLE
Views loaded as demo data

### ISSUE THREAD

**Issue by lflfm** [odoo/tutorials#129]
The gallery view tutorial initial manifest file is loading the views.xml file in the wrong section of the manifest

```
    'demo': [
        'views/views.xml',
    ],
```

Please fix for the `data` section. This is causing a lot of confusion for new students.

**Comment by fdardenne** [comment]
Hello @lflfm,
Thank you for the feedback. I just updated the code to use the data section so that learner are not confused anymore.
