### ISSUE TITLE
Blank page when accessing /owl_playground/playground route

### ISSUE THREAD

**Issue by rossthom** [odoo/tutorials#14]
I am following the OWL Tutorial from the Odoo documentation.
I run Odoo 17 on a python3.11 environment, and using the branch tagges "17.0" from this repository.
When I run odoo 17 with the owl_playground addon installed and want to access the route "/owl_playground/playground", I have a blank page instead of seeing the awaited "Hello World" text.

Here is the full source code of the generated html:
```
<html>
    <head>
        <link type="text/css" rel="stylesheet" href="[/web/assets/a43a684/owl_playground.assets_playground.min.css](view-source:http://localhost:8069/web/assets/a43a684/owl_playground.assets_playground.min.css)"/>
        <script type="text/javascript" src="[/web/assets/6cb9506/owl_playground.assets_playground.min.js](view-source:http://localhost:8069/web/assets/6cb9506/owl_playground.assets_playground.min.js)" onerror="__odooAssetError=1"></script>
    </head>

    <body>
    </body>
</html>
```

**Comment by fdardenne** [comment]
> I am following the OWL Tutorial from the Odoo documentation. I run Odoo 17 on a python3.11 environment, and using the branch tagges "17.0" from this repository. When I run odoo 17 with the owl_playground addon installed and want to access the route "/owl_playground/playground", I have a blank page instead of seeing the awaited "Hello World" text.
> 
> Here is the full source code of the generated html:
> 
> ```
> <html>
>     <head>
>         <link type="text/css" rel="stylesheet" href="[/web/assets/a43a684/owl_playground.assets_playground.min.css](view-source:http://localhost:8069/web/assets/a43a684/owl_playground.assets_playground.min.css)"/>
>         <script type="text/javascript" src="[/web/assets/6cb9506/owl_playground.assets_playground.min.js](view-source:http://localhost:8069/web/assets/6cb9506/owl_playground.assets_playground.min.js)" onerror="__odooAssetError=1"></script>
>     </head>
> 
>     <body>
>     </body>
> </html>
> ```

Hello, thank you for the issue.
The 17.0 tutorial is not up to date yet. We are writing the new one and should be out soon.
In the meantime, you can do it in v16;
