### ISSUE TITLE
Warning: "awesome_tshirt.order.size.required" and "*.state.required" should be Boolean

### ISSUE THREAD

**Issue by rossthom** [odoo/tutorials#15]
On file `awesome_tshirt/models/order.py`, lines 33 and 38, 'required' attribute is initialized with a string `"True"` instead of a boolean `True`.
This generates warnings when starting Odoo.

**Comment by fdardenne** [comment]
Hello, thank you for your feedback. Your issue is now fixed in https://github.com/odoo/tutorials/commit/0aa6a96cc70279788f384828c2865a01df85833c
