### ISSUE TITLE
Wrong Arch Parser: Gallery for V. 17 not working

### ISSUE THREAD

**Issue by planctron** [odoo/tutorials#153]
JS source     awesome_gallery/static/src/gallery_arch_parser.js  causes a stall.

The import   seems to be wrong (for   Odoo 17.0-20240522 )

`> import { XMLParser } from "@web/core/utils/xml";   `                      
XMLParser does not exist!

Possible solution:

```
/** @odoo-module */
import { visitXML } from "@web/core/utils/xml";
export class GalleryArchParser {
    parse(xmlDoc, models, modelName) {
        let imageField = 'image';
        let tooltipField = 'tooltip';
        let limit = 80;
        visitXML(xmlDoc, (node) => {
            if (node.tagName === "gallery") {
                imageField = node.getAttribute("image_field");
                tooltipField = node.getAttribute("tooltip_field");
                limit = node.getAttribute("limit");
            }
        })
        return {
            imageField,
            limit,
            tooltipField,
        };
    }
}
```

**Comment by fdardenne** [comment]
Hello @planctron, thank you for the feedback.
On which branch did you spot this error ? It seems that we already updated it for the v17 
https://github.com/odoo/tutorials/commit/434f3c854ca762fdff8e2ba191eb32368751d739#diff-b5e1f383f5ac27abb97bb049bfbb74cc219bd57f4d80cb3fd96b56e052bde9cbR3
