### ISSUE TITLE
Element img doesn't have required attribute src.

### ISSUE THREAD

**Issue by vzartilas** [odoo/tutorials#2]
https://github.com/odoo/tutorials/blob/711a28e004329e71e22a7e07ae26a64f559bfa07/awesome_tshirt/static/src/image_preview_field/image_preview_field.xml#L5

Error:  Element img doesn't have required attribute src.

The **src attribute is required**, and contains the path to the image you want to embed

`<img t-att-src="props.value" src=""/>`

**Comment by fdardenne** [comment]
Hello @vzartilas,
`t-att-src` will be translated by owl into the `src` attribute so no need to put it manually. For more information of why whe use `t-att` you can take a look at https://github.com/odoo/owl/blob/master/doc/reference/templates.md#dynamic-attributes
