### ISSUE TITLE
JS tutorial 2.3

### ISSUE THREAD

**Issue by dasz-odoo** [odoo/tutorials#6]
the read_group is incorrect in the get_statistics function

orders_by_size = self.read_group([['state', '!=', 'cancelled']], [], ['size'])
-->
orders_by_size = self.read_group([['state', '!=', 'cancelled']], ['size', 'quantity'], ['size'])

or else it fails at this line:
'orders_by_size': {g['size']: g['quantity'] for g in orders_by_size},

**Comment by AntoineVDV** [comment]
@fdardenne

**Comment by dasz-odoo** [comment]
https://github.com/odoo/tutorials/pull/7
heres the pr
